name: publish

on:
  push:
    branches:
    - master
    paths: 
    - 'src/Serilog.Sinks.Fluentd.Http.Json/Serilog.Sinks.Fluentd.Http.Json.csproj'
      
jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build & Test & Pack
      run: |
        dotnet build --no-restore --configuration Release
        dotnet test --no-restore --configuration Release --verbosity normal
        dotnet pack --no-restore --configuration Release --verbosity normal
    - name: Publish  
      run: dotnet nuget push src/Serilog.Sinks.Fluentd.Http.Json/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
